# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-01-24 03:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Buku',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('penulis', models.CharField(max_length=100)),
                ('judul', models.CharField(max_length=100)),
                ('kota', models.CharField(max_length=100)),
                ('penerbit', models.CharField(max_length=100)),
                ('tahun', models.IntegerField()),
            ],
        ),
    ]
